### ISSUE TITLE
TypeError: Object xxx has no method 'primaryLocation'

### ISSUE THREAD

**Issue by HazCod** [robertknight/passcards#63]
Running on Ubuntu, latest git clone

```
./passcards new-vault --iterations 5000 vault

./passcards -d -v vault.agilekeychain add login test
Website: tst.com
Username: test
Password (or '-' to generate a random password): 
TypeError: Object 74A29C5952B04E86AC29A2A14E3E631F has no method 'primaryLocation'
TypeError: Object 74A29C5952B04E86AC29A2A14E3E631F has no method 'primaryLocation'
    at /home/nindustries/source/passcards/build/lib/agile_keychain.js:369:33
    at Array.forEach (native)
    at /home/nindustries/source/passcards/build/lib/agile_keychain.js:360:26
    at Promise_then_fulfilled (/home/nindustries/source/passcards/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/home/nindustries/source/passcards/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/home/nindustries/source/passcards/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/home/nindustries/source/passcards/node_modules/q/q.js:1369:30)
    at RawTask.call (/home/nindustries/source/passcards/node_modules/q/node_modules/asap/asap.js:40:19)
    at flush (/home/nindustries/source/passcards/node_modules/q/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:415:13)
```

**Comment by robertknight** [comment]
Hi @HazCod , which version of node are you using (`node --version`)?

**Comment by robertknight** [comment]
I was able to reproduce the problem, it occurs when using Node 0.10 and ends up using the `Map` class from `es6-collections` rather than the native `Map` class.

The `es6-collections` `Map.forEach()` has the key and value reversed so it ends up trying to call methods on the item ID (the key in an ID -> item map) instead of the item.
